### ISSUE TITLE
dotnet core support

### ISSUE THREAD

**Issue by jiabiao** [CyberSource/cybersource-rest-client-dotnet#14]
Is there a plan to add dotnet core support?

**Comment by jpknoll** [comment]
I'd rather they just targeted netstandard...

**Comment by Digiman** [comment]
I have added this support for library and already created Pull Request #22 (https://github.com/CyberSource/cybersource-rest-client-dotnet/pull/22). Because currently need to use CyberSource API during my work i found that provided library is not fully working. 
Hope i can help more to finish this library.
Thanks.

**Comment by xantari** [comment]
Still no .NET Core support... So sad. They are building this library on old technology

**Comment by xantari** [comment]
@gnongsie @ssethumavisa When can we expect .NET Standard library? Your competitor Stripe has had .NET Standard libraries for a few years now.

**Comment by xantari** [comment]
Anyone home?

**Comment by brutaldev** [comment]
Knock knock... also need a .NET Standard version of this, any ETA?

**Comment by tgandersen** [comment]
Agree with others here.  Very surprised something for .NET Core or .NET Standard isn't available, and that there's been no response one way or the other as far as roadmap for such a thing.  

Can someone from the dev team chime in on whether there will ever be a CyberSource-supported .NET Core or .NET Standard version of this SDK?  Or point us to people who can answer this question?  This is blocking our project and I don't want to have to roll my own solution if something is in the works by CyberSource.

**Comment by brutaldev** [comment]
@tgandersen Also needed a .NET Standard version to run in Linux Docker containers so I forked a copy and updated it. All that's required is a new project file since the code is already .NET Standard compatible (so no idea why they don't just make it a .NET Standard Project).

Since the referenced auth library is only available on NuGet and it's not .NET Standard either, I decompiled and included it in my repo also built for .NET Standard.

1. Clone the code in my fork https://github.com/brutaldev/cybersource-rest-client-dotnet/
2. Open up `CyberSource.Rest.Client.Core.sln` in Visual Studio and build/publish or do it from the command-line.
3. Include the resulting `CyberSource.Authentication.Core.dll` and `CyberSource.Rest.Client.Core.dll` assemblies in your .NET Core project (has all dependencies embedded).

You can verify there are zero code changes other than the decompiled `AuthenticationSdk` assembly and a new .NET Core project: https://github.com/brutaldev/cybersource-rest-client-dotnet/commits/master

**Comment by xantari** [comment]
I think this is the reason why people are switching to Stripe in a mass exodus from Cybersource. Their API platform is light years ahead of what cybersource provides.

Just look at the metrics, 41,117 downloads of CyberSource.Rest.Client, and 5,198,781 downloads of Stripe.net.

**Comment by xantari** [comment]
@brutaldev Isn't it strange how there is no git repo for the AuthenticationSdk and we are resorting to decompiling it.

**Comment by xantari** [comment]
Here is what I got from cybersource today. Looks like there is no priority or roadmap for this feature. Which is odd when it's so easy to do. Guess we gotta use @brutaldev 's repo from now on as it's more up to date.

_Hi Team,

Thank you for your patience on this case. The engineering team has come back to us with their feedback. It seems that there is currently an enhancement ticket on this. But it seems that there is currently no ETA. You may refer to ticket: CYBSDX-31 in the future if you would like an update on the enhancement.

We hope the above was helpful. If you have other questions about the case, please do let us know.

Kind Regards,
Ronna
CyberSource Client Services_

**Comment by brutaldev** [comment]
If Visa/CyberSource don't have a problem with it, I can release my build (on NuGet as well) and deprecate it when they have official support. I'll continue to merge any changes within a day or so after they make updates to this repo to keep it up to date.

**Comment by xantari** [comment]
This issue has been open since Jan 2019, 21 months ago with no fix in site. I'd go for it.

**Comment by gnongsie** [comment]
Hi,

Apologies for the delays for this. We have this in our FY21 plan, and we will provide more information as we flesh out the details.

**Comment by brutaldev** [comment]
NuGet packages available for the .NET Core/Standard version.
https://www.nuget.org/packages/CyberSource.Rest.Client.Core
https://www.nuget.org/packages/CyberSource.Authentication.Core

Updated my repo to version 0.0.1.6 and will continue to keep it up to date and deploy NuGet packages until there is an official.

**Comment by chsriniv9** [comment]
Thank you for feedback and patience. We have Released .Net Standard SDK. Currently it is targeted for **Beta / Non-Production integration** ONLY.

“Please include the following packages using NuGet Package Manager:

CyberSource.Authentication.NetStandard Version="0.0.1"
CyberSource.Rest.Client.NetStandard Version="0.0.1"  

**NuGet Reference** –

•	Cybersource.Authentication.NetStandard - [Latest version: 0.0.1](https://www.nuget.org/packages/Cybersource.Authentication.NetStandard/)
•	CyberSource.Rest.Client.NetStandard by - [Latest version: 0.0.1](https://www.nuget.org/packages/CyberSource.Rest.Client.NetStandard/)

Please drop a note if you need any support during Beta / Non-Production Integration. We will be stand-by to assist.

Ps: Closing this issue as we have released the >support requested. Feel free to re-open if you find any issues.

Thanks Again !!

**Comment by xantari** [comment]
Where is the Git Repo for this?

**Comment by xantari** [comment]
Why is this targeting Net Standard 2.1? You realize you are going to have to maintain two parallel efforts of library maintenace if you don't make it net standard 2.0 right?

**Comment by xantari** [comment]
@chsriniv9 I opened a new issue for these questions.
