### ISSUE TITLE
Link to generate keys in requires incorrect

### ISSUE THREAD

**Issue by aneillans** [CyberSource/cybersource-rest-client-dotnet#55]
The link for keys under requirements leads to a 404 on sample apps.

On this repo, it simply links to the test account page, but there is no clarity on which type of key is required to make this SDK function.

**Comment by gnongsie** [comment]
Hi,
Can you explain which link you are talking about? I see that the link in the README redirects you to a registration page.

You will need to create an evaluation account in order to test this SDK out.

For understanding which key to use and how, please refer to our [Samples repository](https://github.com/CyberSource/cybersource-rest-samples-csharp). There is a section in the README file that explains the keys that you can use.

**Comment by snavinch** [comment]
Closing this issue as there hasn't been any further response
